Table bills {
    id int [pk, increment]
    lab_id int
    user varchar
    created_at datetime
    valid boolean
    paid boolean
}

Table bill_materials {
        bill_id int [ref: > bills.id]
        material_id int [ref: > materials.id]
        quantity int

        indexes {
            (bill_id, material_id) [unique]
        }
    }

Table materials {
    id int [pk, increment]
    nice_name varchar
    system_name varchar
    unit varchar
    cost_per_unit decimal
}

